import '../../common/api/api.dart';
import '../../routes/home/device/card_type_config.dart';
import '../../routes/home/device/grid_container.dart';
import '../../routes/home/device/layout_data.dart';

// 时钟-中，天气-中，线控器1-小，线控器2-小，空填充，空填充
List<Layout> defaultConfigPage = [
  Layout(
      'clock',
      DeviceEntityTypeInP4.Clock,
      CardType.Other,
      0,
      [1, 2, 5, 6],
      DataInputCard(
          name: '时钟',
          applianceCode: 'clock',
          roomName: '屏内',
          isOnline: '',
          type: 'clock',
          masterId: '',
          modelNumber: '',
          onlineStatus: '1')),
  Layout(
      'weather',
      DeviceEntityTypeInP4.Weather,
      CardType.Other,
      0,
      [3, 4, 7, 8],
      DataInputCard(
          name: '天气',
          applianceCode: 'weather',
          roomName: '屏内',
          isOnline: '',
          type: 'weather',
          masterId: '',
          modelNumber: '',
          onlineStatus: '1')),
  Layout(
      'localPanel1',
      DeviceEntityTypeInP4.LocalPanel1,
      CardType.Small,
      0,
      [9, 10],
      DataInputCard(
          name: '灯1',
          applianceCode: 'localPanel1',
          roomName: '屏内',
          isOnline: '',
          type: 'localPanel1',
          masterId: '',
          modelNumber: '',
          onlineStatus: '1')),
  Layout(
      'localPanel2',
      DeviceEntityTypeInP4.LocalPanel2,
      CardType.Small,
      0,
      [11, 12],
      DataInputCard(
          name: '灯2',
          applianceCode: 'localPanel2',
          roomName: '屏内',
          isOnline: '',
          type: 'localPanel2',
          masterId: '',
          modelNumber: '',
          onlineStatus: '1')),
  Layout(uuid.v4(), DeviceEntityTypeInP4.DeviceNull, CardType.Null, 0, [13, 14],
      DataInputCard(name: '', applianceCode: '', roomName: '', isOnline: '', type: '', masterId: '', modelNumber: '', onlineStatus: '')),
  Layout(uuid.v4(), DeviceEntityTypeInP4.DeviceNull, CardType.Null, 0, [15, 16],
      DataInputCard(name: '', applianceCode: '', roomName: '', isOnline: '', type: '', masterId: '', modelNumber: '', onlineStatus: ''))
];

// 不同的面板所使用的卡片类型
Map<String, CardType> panelCardTypeList = {
  '1342': CardType.Big,
  '1341': CardType.Big,
  '1340': CardType.Middle,
  '1339': CardType.Small,
  '1106': CardType.Big,
  '1100': CardType.Small,
  '1104': CardType.Big,
  '1102': CardType.Middle,
  '1087': CardType.Big,
  '1085': CardType.Big,
  '1083': CardType.Middle,
  '1081': CardType.Small,
  '1105': CardType.Big,
  '1103': CardType.Big,
  '1101': CardType.Middle,
  '1099': CardType.Small,
  '67': CardType.Small,
  '68': CardType.Small,
  '69': CardType.Small,
  '70': CardType.Middle,
  '71': CardType.Middle,
  '72': CardType.Middle,
  '73': CardType.Big,
  '74': CardType.Big,
  '75': CardType.Big,
  '76': CardType.Big,
  '43': CardType.Big,
  '42': CardType.Big,
  '41': CardType.Small,
  '37': CardType.Big,
  '36': CardType.Big,
  '35': CardType.Middle,
  '34': CardType.Small,
  '17': CardType.Small,
  '18': CardType.Middle,
  '19': CardType.Big,
  '16': CardType.Big,
  '1344': CardType.Middle,
  '1112': CardType.Middle,
  '1111': CardType.Middle,
  '80': CardType.Middle,
  '81': CardType.Middle,
  '22': CardType.Middle,
  '1350': CardType.Big,
  '1349': CardType.Big,
  '1348': CardType.Middle,
  '1347': CardType.Small,
  '1363': CardType.Big,
  '1362': CardType.Big,
  '1361': CardType.Middle,
  '1360': CardType.Small,
  '1346': CardType.Middle,
  '1345': CardType.Small,
  '1110': CardType.Middle,
  '1108': CardType.Small,
  '1109': CardType.Middle,
  '84': CardType.Small,
  '85': CardType.Small,
  '86': CardType.Middle,
  '87': CardType.Middle,
  '45': CardType.Small,
  '40': CardType.Middle,
  '39': CardType.Small,
  '32': CardType.Middle,
  '31': CardType.Small,
  'homlux1': CardType.Small,
  'homlux2': CardType.Middle,
  'homlux3': CardType.Big,
  'homlux4': CardType.Big,
  'homluxKonbDimmingPanel': CardType.Small,
};

// 单灯的ModelNumber
List<String> singleLightModelNumbers = ['54', '55', '56', '57', '1352', '1353', '1351', '1276', '1359', '1254', '1262', '1263', '3037'];
