/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_midea_aispeech_Mw_Callback */

#ifndef _Included_com_midea_aispeech_Mw_Callback
#define _Included_com_midea_aispeech_Mw_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
