/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_midea_aispeech_Mw */

#ifndef _Included_com_midea_aispeech_Mw
#define _Included_com_midea_aispeech_Mw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_midea_aispeech_Mw
 * Method:    setEventCallback
 * Signature: (Lcom/midea/aispeech/Mw/Callback;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_setEventCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    registerEventDo
 * Signature: (I[Ljava/lang/String;Lcom/midea/aispeech/Mw/Callback;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_registerEventDo
  (JNIEnv *, jclass, jint, jobjectArray, jobject);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    unregisterEvent
 * Signature: (I[Ljava/lang/String;Lcom/midea/aispeech/Mw/Callback;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_unregisterEvent
  (JNIEnv *, jclass, jint, jobjectArray, jobject);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    initDo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_initDo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    unInitDo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_unInitDo
  (JNIEnv *, jclass);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    deviceStatusToCloudResp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_deviceStatusToCloudResp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    playStatusToSpeech
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_playStatusToSpeech
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    audioDataToSpeech
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_audioDataToSpeech
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    beginningTTS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_beginningTTS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    beginningOnlineTTS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_beginningOnlineTTS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    getNLPwithText
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_getNLPwithText
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    settingAccent
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_settingAccent
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    gettingAccent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_midea_aispeech_Mw_gettingAccent
  (JNIEnv *, jclass);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    endOfSpeech
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_endOfSpeech
  (JNIEnv *, jclass);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    createSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_createSession
  (JNIEnv *, jclass);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    registerLicense
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_registerLicense
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_midea_aispeech_Mw
 * Method:    getLicense
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_midea_aispeech_Mw_getLicense
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
